services:
  core:
    build:
        context: .
        dockerfile: Dockerfile

  mysql:
    image: mysql/mysql-server:5.7
    volumes:
      - ./mysql-database-be-careful-with-this:/var/lib/mysql
    environment:
      MYSQL_USER: concour
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: beaver_contest
