services:
  core:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "3200:3200"
  mysql:
    image: mysql/mysql-server:5.7
    volumes:
      - ./mysql-database-be-careful-with-this:/var/lib/mysql
    environment:
      MYSQL_USER: concour
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: beaver_contest
    ports:
      - "3306:3306"

