services:
  core:
    build:
        context: .
        dockerfile: Dockerfile
        args:
          USE_IR: ${USE_IR}
    volumes:
      - ./contests-questions-data-be-careful-with-this:/var/www/html/bebras-platform/contestInterface/contests
    ports:
      - "80:80"
    extra_hosts: {}
#      - "practice-bebras.local:127.0.0.1"
#      - "soal-bebras.local:127.0.0.1"
#      - "admin-bebras.local:127.0.0.1"

  mysql:
    image: mysql/mysql-server:5.7
    user: root
    volumes:
      - `./mysql-database-be-careful-with-this:/var/lib/mysql:rw`
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_USER: concour
        MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}